/*
 * Generated by @medplum/generator
 * Do not edit manually.
 */

import { PoolClient } from 'pg';

export async function run(client: PoolClient): Promise<void> {
  await client.query('ALTER TABLE "ActivityDefinition" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "CapabilityStatement" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "CarePlan" ALTER COLUMN "activityDate" TYPE DATE[]');
  await client.query('ALTER TABLE "ChargeItem" ALTER COLUMN "occurrence" TYPE DATE');
  await client.query('ALTER TABLE "ChargeItemDefinition" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "CodeSystem" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "CommunicationRequest" ALTER COLUMN "occurrence" TYPE DATE');
  await client.query('ALTER TABLE "CompartmentDefinition" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "ConceptMap" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "DetectedIssue" ALTER COLUMN "identified" TYPE DATE');
  await client.query('ALTER TABLE "DeviceRequest" ALTER COLUMN "eventDate" TYPE DATE');
  await client.query('ALTER TABLE "DiagnosticReport" ALTER COLUMN "date" TYPE DATE');
  await client.query('ALTER TABLE "EffectEvidenceSynthesis" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "EventDefinition" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "Evidence" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "EvidenceVariable" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "ExampleScenario" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "Goal" ALTER COLUMN "startDate" TYPE DATE');
  await client.query('ALTER TABLE "Goal" ALTER COLUMN "targetDate" TYPE DATE[]');
  await client.query('ALTER TABLE "GraphDefinition" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "Immunization" ALTER COLUMN "date" TYPE DATE');
  await client.query('ALTER TABLE "ImplementationGuide" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "Library" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "Measure" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "Media" ALTER COLUMN "created" TYPE DATE');
  await client.query('ALTER TABLE "MedicationAdministration" ALTER COLUMN "effectiveTime" TYPE DATE');
  await client.query('ALTER TABLE "MedicationStatement" ALTER COLUMN "effective" TYPE DATE');
  await client.query('ALTER TABLE "MessageDefinition" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "NamingSystem" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "Observation" ALTER COLUMN "date" TYPE DATE');
  await client.query('ALTER TABLE "Observation" ALTER COLUMN "comboValueQuantity" TYPE DOUBLE PRECISION');
  await client.query('ALTER TABLE "Observation" ALTER COLUMN "componentValueQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "Observation" ALTER COLUMN "valueDate" TYPE DATE');
  await client.query('ALTER TABLE "Observation" ALTER COLUMN "valueQuantity" TYPE DOUBLE PRECISION');
  await client.query('ALTER TABLE "OperationDefinition" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "Patient" ALTER COLUMN "deathDate" TYPE DATE');
  await client.query('ALTER TABLE "PlanDefinition" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "Procedure" ALTER COLUMN "date" TYPE DATE');
  await client.query('ALTER TABLE "Provenance" ALTER COLUMN "when" TYPE DATE');
  await client.query('ALTER TABLE "Questionnaire" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "ResearchDefinition" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "ResearchElementDefinition" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "RiskAssessment" ALTER COLUMN "date" TYPE DATE');
  await client.query('ALTER TABLE "RiskAssessment" ALTER COLUMN "probability" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "RiskEvidenceSynthesis" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "SearchParameter" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "ServiceRequest" ALTER COLUMN "occurrence" TYPE DATE');
  await client.query('ALTER TABLE "Specimen" ALTER COLUMN "collected" TYPE DATE');
  await client.query('ALTER TABLE "StructureDefinition" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "StructureMap" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "TerminologyCapabilities" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "TestScript" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
  await client.query('ALTER TABLE "ValueSet" ALTER COLUMN "contextQuantity" TYPE DOUBLE PRECISION[]');
}
